# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    # Rate Limiting
    rate_limiter:
        password_reset:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'
        
        registration:
            policy: 'sliding_window'
            limit: 5
            interval: '24 hours'
        
        email_verification:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
    html_sanitizer:
        sanitizers:
            rich_text:
                allow_safe_elements: true
                allow_elements:
                    a: ['href', 'title', 'target', 'rel']
                allowed_link_schemes: ['http', 'https', 'mailto']
                force_attributes:
                    a:
                        rel: 'noopener noreferrer'
                        target: '_blank'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
