security:

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # 0) Swagger / OpenAPI — PAS DE JWT
        docs:
            pattern: ^/api/docs
            security: false

        # 1) Profiler / assets — PAS DE SÉCURITÉ
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # 2) Login JWT
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # 3) API protégée par JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            custom_authenticator:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:

        # Swagger / OpenAPI → public
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }

        # Login JWT → public
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/test, roles: PUBLIC_ACCESS }

        # Le reste de l'API nécessite un JWT
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        # Pages publiques: connexion autorisée
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/deconnexion, roles: PUBLIC_ACCESS }

        # Back-office admin (EasyAdmin)
        - { path: ^/admin, roles: ROLE_ADMIN }
