# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Service\OrderMailer:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'

    App\Service\StripePaymentService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'
            $publishableKey: '%env(default::STRIPE_PUBLISHABLE_KEY)%'
            $webhookSecret: '%env(default::STRIPE_WEBHOOK_SECRET)%'
            $defaultBaseUrl: '%env(DEFAULT_URI)%'

    App\Image\ImageUploader:
        arguments:
            $projectDir: '%kernel.project_dir%'
